format_version: 10
pipelines:
  tools-automation:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c979c3d:
        git: https://github.com/bharadwaj9git/tools-automation.git
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
      - CREATE:
          fetch_materials: true
          environment_variables: { env: dev }
          approval: { type: manual }
          jobs:
            terraform:
              tasks:
                - exec: { command: terraform , arguments: ["init"] }
                - exec: { command: terraform ,  arguments: ["apply","-auto-approve"] }
